#!/bin/bash
set -eou pipefail

rails plugin new $1
cd $1

sed -i -e 's/^.*TODO.*$//' *.gemspec

rm -rf README.md test/ bin/ lib/tasks MIT-LICENSE Rakefile Gemfile Gemfile.lock

mkdir exe
echo -e "#!/usr/bin/env\nputs '$1-1'" > "exe/$1-1"
echo -e "#!/usr/bin/env\nputs '$1-2'" > "exe/$1-2"
chmod a+x exe/*
