source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# This one is broken 🪲
gem "bar-git", git: "git@github.com:chriscz/bar", branch: 'main'

gem "bar-git-fixed", git: "git@github.com:chriscz/bar-git-fixed", branch: 'main'

gem "bar-path", path: '../bar-path'
